### ISSUE TITLE
Threshold detection to determine relevant tweets from the timeline

### ISSUE THREAD

**Issue by taimoorkhan-nlp** [Alaaeddin103/Rumor_verification#6]
1. Here are some statistical methods for threshold detection. IQR would be my personal preference
We can compare the tweets in a timeline similar to rumor to determine relevant tweets

https://www.researchgate.net/post/Can_someone_suggest_statistical_methods_to_exclude_outliers

2. Clustering can also be helpful in identifying tweets similar to rumor e.g.,  mean-shift with rumor as the center of interest. 

3. Some sophisticated thresholding technique can also be used e.g., Game theoretic rough sets

(1 -> 3, easy to implement, 3 -> 1 effective (in my opinion))

**Comment by taimoorkhan-nlp** [comment]
1) You can tweak the parameters for the clustering approach. 
2) Instead of IQR, you can use semi-quartile range which is technically IQR/2 (https://byjus.com/maths/interquartile-range/)

**Comment by Alaaeddin103** [comment]
I updated the module withe your suggestion
